Update onedrive-d

diff --git a/Business/onedrive-d b/Business/onedrive-d
--- a/Business/onedrive-d
+++ b/Business/onedrive-d
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+local_folder="$1"
 exec_path=$(readlink -f "$0")
 export script_base_folder=$(dirname "$exec_path")
 
@@ -24,9 +25,15 @@ function get_local_folder() {
       done
     }
 
-local_folder="$1"
-dir -d "${local_folder}" >/dev/null 2>&1;
-[ $? -ne '0' ] && echo 'Error! Not access to the folder.' && exit 1
-cd "${local_folder}"
-local_folder_base="$(dirname $(readlink -f ./))"
-get_local_folder;
+if [[ -d "${local_folder}" ]]; then
+  dir -d "${local_folder}" >/dev/null 2>&1;
+  if [[ $? -ne '0' ]]; then
+    echo 'Error! Not access to the folder.';
+    exit 1;
+  fi
+  cd "${local_folder}";
+  local_folder_base="$(dirname $(readlink -f ./))";
+  get_local_folder;
+elif [[ -f "${local_folder}" ]]; then
+  eval "${script_base_folder}/onedrive" \'$local_folder\';
+fi
